### ISSUE TITLE
WPML All Import breaks WP All Import User Imports

### ISSUE THREAD

**Issue by llos** [wp-premium/wpml-all-import#2]
I am trying to import users using WP All Import but this works only when I have WPML All Import disabled. Is this something you can control from your side? We need to have WPML All Import enabled because we have cronjobs of imports that needs it.
I already posted this here https://wpml.org/forums/topic/wpml-all-import-breaks-wp-all-import-user-imports/ some time ago without success.
Thanks!

**Comment by remcotolsma** [comment]
> This repository is just a mirror of the MemberPress plugin. **Please do not send pull requests and issues.**

https://github.com/wp-premium/wpml-all-import
